import "./globals.css";
import NavBar from "@/components/NavBar";
import Providers from "./providers";

export const metadata = {
  title: "Full Stack App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Providers>
          <NavBar />
          <main className="flex-grow flex justify-center">
            <div className="w-full max-w-6xl px-4 py-8">{children}</div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
